---

- name: is Vagrant already installed?
  action: command which vagrant
  register: vagrant_which
  ignore_errors: true

- name: download Vagrant
  action: get_url url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.4.0_x86_64.deb dest=/tmp/vagrant_1.4.0_x86_64.deb
  when: "'vagrant' not in vagrant_which.stdout"

- name: install Vagrant
  action: command dpkg -i /tmp/vagrant_1.4.0_x86_64.deb
  sudo: True
  when: "'vagrant' not in vagrant_which.stdout"