---

- name: is Vagrant already installed?
  action: command which vagrant
  register: vagrant_which
  ignore_errors: true

- name: download Vagrant
  action: get_url url=http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb dest=/tmp/vagrant_1.2.2_x86_64.deb
  when: "'vagrant' not in vagrant_which.stdout"

- name: install Vagrant
  action: command dpkg -i /tmp/vagrant_1.2.2_x86_64.deb
  sudo: True
  when: "'vagrant' not in vagrant_which.stdout"