---
- include: pear.yml
- include: apc.yml
- include: curl.yml
- include: json.yml
- include: redis_inspect.yml
- include: redis_install.yml
  when: "php_redis_installed == 'false'"
- include: sqlite.yml
- include: xdebug.yml
- include: yaml_inspect.yml
- include: yaml_install.yml
  when: "php_yaml_installed == 'false'"
- include: phix_inspect.yml
- include: phix_install.yml
  when: "phix_installed == 'false'"