---

- name: install libYAML-dev
  action: apt pkg=libyaml-dev state=latest
  sudo: True

- name: copy YAML script
  action: copy src=php-yaml.exp dest=/tmp/php-yaml.exp mode=0700

- name: install YAML pecl module
  action: command /tmp/php-yaml.exp
  sudo: True

- name: install YAML config file
  action: copy src=yaml.ini dest=/etc/php5/conf.d/yaml.ini
  sudo: True
  notify:
  - restart Apache