---
- name: download Vagrant
  action: get_url url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{vagrant_version}}_x86_64.deb dest=/tmp/vagrant_{{vagrant_version}}_x86_64.deb

- name: install Vagrant
  action: command dpkg -i /tmp/vagrant_{{vagrant_version}}_x86_64.deb
  sudo: True
