---

- name: is NodeJS already installed?
  action: command node --version
  register: nodejs_which
  ignore_errors: true

- name: download NodeJS source code
  action: get_url url=http://nodejs.org/dist/v${node_version}/node-v${node_version}.tar.gz dest=/tmp/node-v${node_version}.tar.gz
  sudo: False
  when: "'${node_version}' not in nodejs_which"

- name: unpack NodeJS source code
  action: command tar -zxf /tmp/node-v${node_version}.tar.gz creates=/tmp/node-v${node_version} chdir=/tmp
  sudo: False
  when: "'${node_version}' not in nodejs_which"

- name: compile NodeJS
  action: command make -j chdir=/tmp/node-v${node_version}
  sudo: False
  when: "'${node_version}' not in nodejs_which"

- name: install NodeJS
  action: command make install chdir=/tmp/node-v${node_version}
  sudo: True
  when: "'${node_version}' not in nodejs_which"
