---

- name: Is Jekyll already installed?
  action: command which jekyll
  register: jekyll_which
  ignore_errors: true

- name: Install Jekyll
  action: command gem install jekyll
  sudo: True
  when: "'jekyll' not in jekyll_which.stdout"