---

- name: create the folder to download the Redis server into
  action: file path=/home/$user/Devel/redis.io state=directory
  sudo: False

- name: download Redis source code
  action: get_url url=http://redis.googlecode.com/files/redis-${redis_version}.tar.gz dest=/home/$user/Devel/redis.io/redis-${redis_version}.tar.gz
  sudo: False

- name: unpack the Redis source code
  action: command tar -zxf redis-${redis_version}.tar.gz chdir=/home/$user/Devel/redis.io
  sudo: False

- name: compile Redis Server
  action: command make chdir=/home/$user/Devel/redis.io/redis-${redis_version}